# Site settings
#开头
title: 老胡同学 -- 既然选择了远方，便只顾风雨兼程。
email: husheng.student@foxmail.com
description:
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
#链接
github_username: HushengStudent
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
# viewsourceroot: https://github.com/HushengStudent
# this is the url root of the create page link on the footer page.
# newsourceroot: https://github.com/HushengStudent
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#评论
#disqus_shortname: 胡胜同学
#disqus_url: "https://hushengstudent.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
